#!/usr/bin/perl

ifeq ($(MTK_EMMC_SUPPORT),yes)
BOARD_PROTECT_FIMAGE_PARTITION_SIZE:=10M
BOARD_PROTECT_SIMAGE_PARTITION_SIZE:=10M
BOARD_SECROIMAGE_PARTITION_SIZE:=6M
BOARD_SYSTEMIMAGE_PARTITION_SIZE:=750M
BOARD_CACHEIMAGE_PARTITION_SIZE:=512M
BOARD_USERDATAIMAGE_PARTITION_SIZE:=15044M
BOARD_FATIMAGE_PARTITION_SIZE:=0M
endif 
